export const initCompanyValue = {
  Name: "",
  Idc: "",
  ParentDepartmentOid: "",
  Ordinal: "",
  PhoneNumber:"",
  Email : "",
  Photo:"",
  Type: "",
  ReceivingLevel : "",
  StaffPhoneNumber : "",
  HeadPhoneNumber : "",
  StaffEmail: "",
  EmailOfTheHead : "",
  EmailCchc1 : "",
  EmailCchc2 : "",
  AgencyNameSms : "",
  PostalCode : "",
  IsNhanHslienThong : "",
  TaxCode : "",
  CountryManagementCode : "",
  IsCheckInvoicePrinting : "",
  InvoiceSymbolNumber : "",
  BeneficiaryAccountNumber : "",
  BeneficiaryAccountName : "",
  BeneficiaryBankCodeDvcqg : "",
  BeneficiaryBankNameDvcqg : "",
  StateTreasuryAccountNumber : "",
  StateTreasuryAccountCode : "",
  StateTreasuryAccountName : "",
  IsConnectResidential : "",
  KeyConnectElectronicResidential : "",
  Hrmoid : "",
  HrmchaOid : "",
  IsParent : "",
  Departments : "",
  JoinUnit : "",
  JoninUnitGroup : ""
};
